{% set name = "harminv" %}
{% set version = "1.4.1" %}
{% set sha256 = "e1b923c508a565f230aac04e3feea23b888b47d8e19b08816a97ee4444233670" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/NanoComp/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1005
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make
  host:
    - openblas  # [ linux ]
    - openblas  # [ osx ]
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libharminv${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/NanoComp/harminv
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Harmonic inversion algorithm of Mandelshtam - decompose signal into sum of decaying sinusoids
  #doc_url: https://harminv.readthedocs.io
  dev_url: https://github.com/NanoComp/harminv

extra:
  recipe-maintainers:
    - ChristopherHogan
    - oskooi
