{% set version = "1.4.2" %}

package:
  name: harminv
  version: {{ version }}

source:
  url: https://github.com/NanoComp/harminv/releases/download/v{{ version }}/harminv-{{ version }}.tar.gz
  sha256: 5a9a1bf710972442f065d0d62c62d0c4ec3da4a3696d7160a35602c9470bc7a2

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - libblas
    - libcblas
    - liblapack
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libharminv${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/NanoComp/harminv
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Harmonic inversion algorithm of Mandelshtam - decompose signal into sum of decaying sinusoids
  #doc_url: https://harminv.readthedocs.io
  dev_url: https://github.com/NanoComp/harminv

extra:
  recipe-maintainers:
    - oskooi
